spring.datasource.url=jdbc:postgresql://localhost:5432/wealthmgmt
spring.datasource.username=gauravsharma
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=true

server.port=8080
